//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class AppNetUserType
    {
        [Display(Name = "Tên đăng nhập")]
        public string Username { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        [Display(Name = "Địa chỉ")]
        public string Address { get; set; }
        [Display(Name = "Điện thoại")]
        public string Phone { get; set; }
        [Display(Name = "Loại người dùng")]
        public string UserType { get; set; }
        [Display(Name = "Ngày tạo")]
        public string DateCreate { get; set; }
        [Display(Name = "Ngày hết hạn")]
        public string Expire { get; set; }
        [Display(Name = "Tỉnh/Thành phố")]
        public int LocationID { get; set; }
        [Display(Name = "Quận huyện")]
        public string District { get; set; }
        [Display(Name = "Trạng thái")]
        public string State { get; set; }
        [Display(Name = "Mã số thuế")]
        public string TaxID { get; set; }
        [Display(Name = "Tên cá nhân/đại lý")]
        public string DisplayName { get; set; }
    }
}
