//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class OrdersDetail
    {
        public long ID { get; set; }
        [Display(Name = "Sản phẩm")]
        public long IDProduct { get; set; }
        [Display(Name = "Giá")]
        public decimal Price { get; set; }
        [Display(Name = "Sô lượng")]
        public int Amount { get; set; }
        [Display(Name = "Hàng trả")]
        public bool ReturnGood { get; set; }
        [Display(Name = "Ngày lập")]
        public Nullable<System.DateTime> DateOfOrder { get; set; }
        [Display(Name = "Thuế suất")]
        public Nullable<long> Tax { get; set; }
        [Display(Name = "Tổng cộng")]
        public decimal Total { get; set; }
        [Display(Name = "Mô tả")]
        public string Description { get; set; }
        [Display(Name = "Mã sản phẩm")]
        public string ProductCode { get; set; }
        [Display(Name = "Yêu cầu từ khách hàng")]
        public bool RequestByUser { get; set; }
    }
}
