//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersDetail
    {
        public int ID { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<long> Price { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<bool> ReturnGood { get; set; }
        public Nullable<System.DateTime> DateOfOrder { get; set; }
        public Nullable<long> Tax { get; set; }
        public Nullable<long> Total { get; set; }
        public string Description { get; set; }
    }
}
