//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public long ProductID { get; set; }
        public bool Active { get; set; }
        public string PromotionCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int UserID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public int PromotionTypeID { get; set; }
        public decimal PromotionValue { get; set; }
        public long ID { get; set; }
    }
}
